/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainPackage;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author sid
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelFirstName = new javax.swing.JLabel();
        LabelLastName = new javax.swing.JLabel();
        LabelAge = new javax.swing.JLabel();
        LabelEmailID = new javax.swing.JLabel();
        TextFirstName = new javax.swing.JTextField();
        TextLastName = new javax.swing.JTextField();
        TextAge = new javax.swing.JTextField();
        TextEmailID = new javax.swing.JTextField();
        LabelPhoto = new javax.swing.JLabel();
        ButtonUpload = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        ButtonSubmit = new javax.swing.JButton();
        LabelPhone = new javax.swing.JLabel();
        TextPhone = new javax.swing.JTextField();
        LabelUserProfile = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();
        canvas3 = new java.awt.Canvas();
        canvas4 = new java.awt.Canvas();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(149, 224, 242));

        LabelFirstName.setText("First Name :");

        LabelLastName.setText("Last Name :");

        LabelAge.setText("Age :");

        LabelEmailID.setText("Email ID :");

        TextFirstName.setToolTipText("Enter your first name");
        TextFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFirstNameActionPerformed(evt);
            }
        });

        TextLastName.setToolTipText("Enter your last name");
        TextLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLastNameActionPerformed(evt);
            }
        });

        TextAge.setToolTipText("Enter your age");

        TextEmailID.setToolTipText("Enter your email ID");

        LabelPhoto.setText("Photo");

        ButtonUpload.setText("Upload");
        ButtonUpload.setToolTipText("Click to upload from your files");
        ButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUploadActionPerformed(evt);
            }
        });

        ButtonCancel.setText("Cancel");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        ButtonSubmit.setText("Submit");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        LabelPhone.setText("Phone Number:");

        TextPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPhoneActionPerformed(evt);
            }
        });

        LabelUserProfile.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LabelUserProfile.setText("USER PROFILE");
        LabelUserProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelEmailID)
                            .addComponent(LabelPhone)
                            .addComponent(LabelAge)
                            .addComponent(LabelLastName)
                            .addComponent(LabelFirstName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelPhoto)
                                .addGap(23, 23, 23))
                            .addComponent(ButtonCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextAge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ButtonUpload)
                                            .addComponent(ButtonSubmit))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(canvas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(TextEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(LabelUserProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelUserProfile)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFirstName)
                    .addComponent(TextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLastName)
                    .addComponent(TextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAge)
                    .addComponent(TextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPhone)
                    .addComponent(TextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmailID)
                    .addComponent(TextEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonUpload)
                            .addComponent(LabelPhoto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(canvas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(canvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(canvas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCancel)
                    .addComponent(ButtonSubmit))
                .addGap(35, 35, 35)
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        TextFirstName.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFirstNameActionPerformed

    private void TextLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLastNameActionPerformed
Image a=null;
    private void ButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUploadActionPerformed
        // TODO add your handling code here:
//        JFileChooser fileChooser = new JFileChooser();
//        fileChooser.showOpenDialog(null);
//        File f = fileChooser.getSelectedFile();
//        String path = f.getAbsolutePath();
            JFileChooser file = new JFileChooser();
if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
try {
BufferedImage img = ImageIO.read(file.getSelectedFile());
Image edited_image = img.getScaledInstance(60, 80,
Image.SCALE_SMOOTH);

if (edited_image != null) {
    a=edited_image;
//LabelPhoto.setText(file.getSelectedFile().getAbsolutePath());
//this.ButtonUpload.setPic(new ImageIcon(edited_image));
//this.jLabel1.setIcon(new ImageIcon(edited_image));
}
} catch (Exception ex) {
JOptionPane.showMessageDialog(this, "Please upload image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();
}
}

    }//GEN-LAST:event_ButtonUploadActionPerformed

    private void TextPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPhoneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextPhoneActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        // TODO add your handling code here:
        TextFirstName.setText(null);
        TextLastName.setText(null);
        TextAge.setText(null);
        TextPhone.setText(null);
        TextEmailID.setText(null);
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
        // TODO add your handling code here:
        int isValid=1;
        String dialogValueSuccess = "";
        String dialogValueFail = "";
        
        String FnameValue = TextFirstName.getText();
        
        String LnameValue = TextLastName.getText();
        
        String AgeValue = TextAge.getText();
        
        String PhoneValue = TextPhone.getText();
        
        String EmailValue = TextEmailID.getText();
        
        String PhotoValue = ButtonUpload.getText();
        
        if(FnameValue.matches("[a-zA-Z]+")){
        dialogValueSuccess = dialogValueSuccess+ "\nFirst Name is\t"+FnameValue;
        //JOptionPane.showMessageDialog(this , dialogValueSuccess);
        }
        else{
        dialogValueFail = dialogValueFail+ "\nIncorrect First Name\t"+FnameValue;
        isValid=0;
        }
        
        if(LnameValue.matches("[a-zA-Z]+")){
        dialogValueSuccess = dialogValueSuccess+ "\nLast Name is\t"+LnameValue;
        }
        else{
        dialogValueFail = dialogValueFail+ "\nIncorrect Last Name\t"+LnameValue;
        isValid=0;
        }
        
        if(AgeValue.matches("^[0-9]*$") && AgeValue.length ()==2) {
        dialogValueSuccess = dialogValueSuccess+ "\nAge is\t"+AgeValue;
        }
        else{
        dialogValueFail = dialogValueFail+ "\nIncorrect Age\t"+AgeValue;
        isValid=0;
        }
       
        if(PhoneValue.matches("^[0-9]*$") && PhoneValue.length ()==10) {
        dialogValueSuccess = dialogValueSuccess+ "\nPhone number is\t"+PhoneValue;
        }
        else{
        dialogValueFail = dialogValueFail+ "\nIncorrect Phone Number\t"+PhoneValue;
        isValid=0;
        }
        
        if(EmailValue.matches("[a-zA-Z0-9.%-]+@[a-zA-Z0-9-]+.[a-zA-Z]{2,4}" )){
        dialogValueSuccess = dialogValueSuccess+ "\nEmail ID is\t"+EmailValue;
        }
        else{
        dialogValueFail = dialogValueFail+ "\nIncorrect Email ID\t"+EmailValue;
        isValid=0;
        }
        
        if(isValid==1){
        JOptionPane.showMessageDialog(this , dialogValueSuccess,"Success",1,new ImageIcon(a));
        }
        else{
//        JOptionPane.showMessageDialog(this , dialogValueFail,"Error",0,new ImageIcon(a));
        JOptionPane.showMessageDialog(this, dialogValueFail);
        }
    }//GEN-LAST:event_ButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JButton ButtonUpload;
    private javax.swing.JLabel LabelAge;
    private javax.swing.JLabel LabelEmailID;
    private javax.swing.JLabel LabelFirstName;
    private javax.swing.JLabel LabelLastName;
    private javax.swing.JLabel LabelPhone;
    private javax.swing.JLabel LabelPhoto;
    private javax.swing.JLabel LabelUserProfile;
    private javax.swing.JTextField TextAge;
    private javax.swing.JTextField TextEmailID;
    private javax.swing.JTextField TextFirstName;
    private javax.swing.JTextField TextLastName;
    private javax.swing.JTextField TextPhone;
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private java.awt.Canvas canvas3;
    private java.awt.Canvas canvas4;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
